import { createClient } from '@/lib/supabase/server'
import { verifyOrgMembership } from '@/lib/utils-server'
import { NextResponse } from 'next/server'

// GET: Get all active VAT rates for organization
export async function GET(
  request: Request,
  { params }: { params: Promise<{ orgId: string }> }
) {
  const { orgId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })
  }

  const isMember = await verifyOrgMembership(orgId)
  if (!isMember) {
    return NextResponse.json({ error: 'Not authorized' }, { status: 403 })
  }

  const { searchParams } = new URL(request.url)
  const includeInactive = searchParams.get('includeInactive') === 'true'

  const query = supabase
    .from('vat_rates')
    .select('*')
    .eq('org_id', orgId)
    .order('created_at', { ascending: true })

  if (!includeInactive) {
    query.eq('is_active', true)
  }

  const { data: vatRates, error } = await query

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 400 })
  }

  return NextResponse.json({ vatRates: vatRates || [] })
}

// POST: Create new VAT rate
export async function POST(
  request: Request,
  { params }: { params: Promise<{ orgId: string }> }
) {
  const { orgId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })
  }

  const isMember = await verifyOrgMembership(orgId)
  if (!isMember) {
    return NextResponse.json({ error: 'Not authorized' }, { status: 403 })
  }

  const body = await request.json()
  const { rate, is_default } = body

  // Validate rate
  if (rate === undefined || rate === null) {
    return NextResponse.json({ error: 'Rate is required' }, { status: 400 })
  }

  const rateNum = Number(rate)
  if (isNaN(rateNum) || rateNum < 0 || rateNum > 100) {
    return NextResponse.json({ error: 'Rate must be between 0 and 100' }, { status: 400 })
  }

  // Check if rate already exists for this org
  const { data: existing } = await supabase
    .from('vat_rates')
    .select('id')
    .eq('org_id', orgId)
    .eq('rate', rateNum)
    .eq('is_active', true)
    .maybeSingle()

  if (existing) {
    return NextResponse.json({ error: 'A VAT rate with this percentage already exists' }, { status: 400 })
  }

  // If setting as default, unset other defaults
  if (is_default) {
    await supabase
      .from('vat_rates')
      .update({ is_default: false })
      .eq('org_id', orgId)
      .eq('is_default', true)
  }

  // Insert new VAT rate (name will be auto-generated by database trigger)
  const { data: vatRate, error } = await supabase
    .from('vat_rates')
    .insert({
      org_id: orgId,
      name: '', // Will be auto-generated by trigger
      rate: rateNum,
      is_default: is_default || false,
      is_active: true,
    })
    .select()
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 400 })
  }

  return NextResponse.json({ vatRate })
}
